b,c,d=map(int,input().split())
B=list(map(int,input().split()))
C=list(map(int,input().split()))
D=list(map(int,input().split()))
B.sort(reverse=True)
C.sort(reverse=True)
D.sort(reverse=True)
m = min(b,c,d)
burger = sum(B) - 0.1*sum(B[:m])
side = sum(C) - 0.1*sum(C[:m])
dissert = sum(D) - 0.1*sum(D[:m])
print(sum(B)+sum(C)+sum(D))
print(int(burger+side+dissert))
